backend:
  name: git-gateway

media_folder: static/assets
public_folder: /assets

collections: 
  - name: post
    label: Samples
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: image, label: Image, widget: image }
      - { name: sample, label: Sample Number }
      - { name: link, label: Link }
      - { name: date, label: Published On, widget: date }
      - { name: body, label: Content, widget: markdown }
